from datetime import datetime

from sqlalchemy import DateTime, Index, Text, func
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from backend.models.base import Base


class Project(Base):
    """A saved workspace. Created empty from the sidebar's "+" button, then filled in on save.

    The JSONB columns are frozen frontend snapshots (graph, market cards, evidence): the
    backend stores them as-is and never queries inside them, so their shape is owned by
    frontend/src/types/*.ts rather than duplicated as tables here.
    """

    __tablename__ = "projects"

    id: Mapped[str] = mapped_column(Text, primary_key=True)  # uuid4, generated by the API
    name: Mapped[str] = mapped_column(Text)
    ticker: Mapped[str | None] = mapped_column(Text)  # null until a graph is built
    graph_snapshot: Mapped[dict | None] = mapped_column(JSONB)
    selected_market_ids: Mapped[list[str]] = mapped_column(ARRAY(Text), server_default="{}")
    suggested_markets: Mapped[list[dict]] = mapped_column(JSONB, server_default="[]")
    evidence: Mapped[list[dict]] = mapped_column(JSONB, server_default="[]")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


Index("projects_updated_at", Project.updated_at.desc())
